# Generated by Django 6.0.4 on 2026-04-17 17:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consentimento_dados',
            field=models.BooleanField(default=True, help_text='Consentimento para armazenamento de dados pessoais'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_acesso_ultima',
            field=models.DateTimeField(blank=True, help_text='Última vez que o perfil foi acessado', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_consentimento',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Data e hora do consentimento'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('total_itens', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrinho de Compras',
                'verbose_name_plural': 'Carrinhos de Compras',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_no_momento', models.DecimalField(decimal_places=2, help_text='Preço quando o item foi adicionado', max_digits=10)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='products.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Item do Carrinho',
                'verbose_name_plural': 'Itens do Carrinho',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
