# Generated by Django 6.0.4 on 2026-04-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_userprofile_consentimento_dados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('produtos_atualizados', models.IntegerField(default=0, help_text='Quantidade de produtos atualizados nesta sincronização')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro'), ('partial', 'Parcial')], default='success', max_length=20)),
                ('detalhes', models.TextField(blank=True, help_text='Detalhes da sincronização', null=True)),
            ],
            options={
                'verbose_name': 'Registro de Sincronização',
                'verbose_name_plural': 'Registros de Sincronização',
                'ordering': ['-timestamp'],
            },
        ),
    ]
